PidFile /var/run/c-icap.pid
CommandsSocket /var/run/c-icap/c-icap.ctl
Timeout 300
MaxKeepAliveRequests 100
KeepAliveTimeout 600
StartServers 1
MaxServers 5
MinSpareThreads 5
MaxSpareThreads 10
ThreadsPerChild 5
MaxRequestsPerChild 0
Port 1344
ServerAdmin admin@localhost
ServerName squidscas-icap
TmpDir /tmp

Module logger sys_logger.so
Logger sys_logger
sys_logger.Facility local6

Service squidscas squidscas.so
