maxsize 100M
redirect http://127.0.0.1/scas-error
scan_mode ScanAllExcept

scanpath /usr/local/var/scan
memcached_servers memcached:11211
blacklist /etc/squid/blacklist_bump
servicelist /etc/squid/scas_service.conf
viruslist /etc/squid/virus
